#!/bin/bash

num1=5
num2=4

num3=$((num1 + num2))
num4=$((num1 - num2))
num5=$((num1 * num2))
num6=$((num1 / num2))
num7=$((num1 ** num2))
num8=$((num1 % num2))

echo "5 + 4 = $num3"
echo "5 - 4 = $num4"
echo "5 * 4 = $num5"
echo "5 / 4 = $num6"
echo "5 ** 4 = $num7"
echo "5 % 4 = $num8"

