#!/bin/bash

str1=""
str2="Sunny Saturday"
str3="Cloudy Monday"

if [ $str1 ]; then
	echo "$str1 is not null"
fi

if [ -z $str1 ]; then
	echo "$str1 exists but is null"
fi

if [ "$str2" == "$str3" ]; then
	echo "$str2 equals $str3"
elif [ "$str2 != "str3 ]; then
	echo "$str2 is not equal to $str3"
fi

if [ "$str2" > "$str3" ]; then
	echo "$str2 is greater then $str3"
elif [ "$str2" < "$str3" ]; then
	echo "$str2 is les then $str3"
fi

