#!/bin/bash

echo "Welcome to Command Menu!"
echo "D or d for printing date"
echo "U or u for printing online usernames"
echo "W or w for printing current working directory"
echo "L or l for listing all the directories and files under current directory"
echo "Q or q for qutting the program"
echo 

read -p "Please enter a letter: " letter

while  [ "$letter" ]; do

case $letter in

[dD])
	date
	;;

[uU])
	users
	;;

[wW])
	pwd
	;;

[lL])
	ls
	;;

[qQ])
	exit
	;;

esac

read -p "Please enter a letter: " letter

done
