#!/bin/bash

read -p "Enter A, B, or C: " letter

if [ "$letter" == "A" ]; then
	echo "You entered A."

elif [ "$letter" == "B" ]; then
	echo "You entered B."

elif [ "$letter" == "C" ]; then 
	echo "You entered C."

else
	echo "You did not enter A, B, or C."

fi
