#!/bin/bash

file1="$(ls -l "$1" | cut -f1 -d' ')"
file2="$(ls -l "$2" | cut -f1 -d' ')"

if [[ -f "$1"  && -f "$2" ]]; then
	if [[ "$file1" == "$file2" ]]; then
		echo "$file1"

	else
		echo "$1: $file1"
		echo "$2: $file2"
	fi

fi

	

